name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: [1.19.x, 1.20.x, 1.21.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
        
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        env:
          ACCOUNTID: ${{ secrets.ACCOUNTID }}
          LICENSEKEY: ${{ secrets.LICENSEKEY }}
        run: go test ./cmd/tests/...
